default: 
  adapter: postgresql
  encoding: unicode
  host: localhost
  password: xxxxxxx
  port: 5432
  username: postgres
development: 
  adapter: postgresql
  database: stkscrapbook_development
  encoding: unicode
  host: localhost
  password: xxxxxxx
  port: 5432
  username: postgres
production: 
  adapter: postgresql
  database: stkscrapbook-production
  encoding: unicode
  host: stkscrapbook-production.postgres.database.azure.com
  password: xxxxxxx
  post: 5432
  username: postgres@stkscrapbook-production
test: 
  adapter: postgresql
  database: stkscrapbook_test
  encoding: unicode
  host: localhost
  password: xxxxxxx
  port: 5432
  username: postgres
